// Generated by CoffeeScript 1.9.2
var cluster;

cluster = require('cluster');

module.exports = function(cb) {
  var toma;
  if (cluster.isWorker) {
    return cb();
  }
  toma = {};
  cluster.on('exit', function(worker) {
    if (toma[worker.id] == null) {
      return cluster.fork();
    }
  });
  cluster.fork();
  process.on('SIGHUP', function() {
    var worker;
    worker = cluster.fork();
    return worker.once('listening', function(address) {
      var child, id, ref, results;
      ref = cluster.workers;
      results = [];
      for (id in ref) {
        child = ref[id];
        if (id === worker.id.toString()) {
          continue;
        }
        toma[id] = true;
        results.push(child.process.kill());
      }
      return results;
    });
  });
  return process.on('SIGTERM', function() {
    var i, id, len, ref, results;
    ref = cluster.workers;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      id = ref[i];
      toma[worker.id] = true;
      results.push(cluster.workers[id].process.kill());
    }
    return results;
  });
};
